### ISSUE TITLE
Incorrect processing of URLs for font-face

### ISSUE THREAD

**Issue by kostik-noir** [miloszsobczak/less-src-replace#1]
# As an example

Original code from bootstrap. Pay attention to the values of "src" on the lines that contains 
- format('embedded-opentype')
- format('svg')

``` css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('@{icon-font-path}@{icon-font-name}.eot');
  src: url('@{icon-font-path}@{icon-font-name}.eot?#iefix') format('embedded-opentype'),
       url('@{icon-font-path}@{icon-font-name}.woff2') format('woff2'),
       url('@{icon-font-path}@{icon-font-name}.woff') format('woff'),
       url('@{icon-font-path}@{icon-font-name}.ttf') format('truetype'),
       url('@{icon-font-path}@{icon-font-name}.svg#@{icon-font-svg-id}') format('svg');
}
```
# Wrong result
- the line which contains "format('embedded-opentype')" does not have suffix "?#iefix"
- the line which contains "format('svg')" contains incorrect URL

``` css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('css-assets/99718da6e37fa5ecd783c05da5776a27-glyphicons-halflings-regular.eot');
  src: url('css-assets/99718da6e37fa5ecd783c05da5776a27-glyphicons-halflings-regular.eot') format('embedded-opentype'), 
         url('css-assets/35235a935962823d0e87d0e906dbd4fc-glyphicons-halflings-regular.woff2') format('woff2'), 
         url('css-assets/2d3fceb5714523e1a20953bab085993b-glyphicons-halflings-regular.woff') format('woff'), 
         url('css-assets/88e79c0ab6e846d320a558acfced1a1f-glyphicons-halflings-regular.ttf') format('truetype'), 
         url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
# Expected

``` css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('css-assets/99718da6e37fa5ecd783c05da5776a27-glyphicons-halflings-regular.eot');
  src: url('css-assets/99718da6e37fa5ecd783c05da5776a27-glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
       url('css-assets/35235a935962823d0e87d0e906dbd4fc-glyphicons-halflings-regular.woff2') format('woff2'),
       url('css-assets/2d3fceb5714523e1a20953bab085993b-glyphicons-halflings-regular.woff') format('woff'),
       url('css-assets/88e79c0ab6e846d320a558acfced1a1f-glyphicons-halflings-regular.ttf') format('truetype'),
       url('css-assets/21406e5a5866a32b2cc21bb7f9083262-glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
